spring.application.name=state-info-app


spring.datasource.url=jdbc:postgresql://localhost:5432/l2t_db
spring.datasource.username=dbadmin
spring.datasource.password=db1dm2n

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:main-migration/main-liquibase.xml